### ISSUE TITLE
Unable to change skin

### ISSUE THREAD

**Issue by kirill-lappo-dgt** [adamyg/mcwin32#11]
## Description

All skin names are trimed from start by 2 letters, and user can't select any other skin.

Same issue in both Windows Terminal and classic terminal window. Window resize does not affect the behaviour.

## Screenshots
Seems like it should be `Featured`(?) or `Seasons`
![image](https://user-images.githubusercontent.com/96829169/148053291-e00215c1-3b51-44f6-97e2-d05eb27fdca4.png)
![image](https://user-images.githubusercontent.com/96829169/148053370-6d6d82bf-b32e-4a35-9ff9-fec6a76e8169.png)

## Temporary Workaround 

1. Close MC
2. Open `~/Midnight Commander/ini`
3. Change `skin` parameter value, for ex. `skin=modarin256`
4. Open MC, selected theme will be applied.

## Tech Details

```
GNU Midnight Commander 4.8.24
Built with GLib 2.51.4
Built with S-Lang 3.0.0 libw32 with terminfo database
With builtin Editor
With mouse support on xterm
With internationalization support
With multiple codepages support
Virtual File Systems:
 cpiofs, tarfs, sfs, extfs, ftpfs, sftpfs
Data types:
 char: 8; int: 32; long: 32; void *: 32; size_t: 32; off_t: 32;
```

**Comment by adamyg** [comment]
_wopendir linkage clash  between libglib/libw32 and run-time.

**Comment by adamyg** [comment]
build-223 pending

**Comment by adamyg** [comment]
4.8.24.223
