### ISSUE TITLE
Change default language

### ISSUE THREAD

**Issue by hunorbsd** [adamyg/mcwin32#13]
Hi,
Is there a way to change the MC interface language, it seems that it is picking up from the regional settings.
I use English for main system but other language for regional purposes (for date, delimiters etc.)

I would like to default MC to English.

Thank you.

**Comment by adamyg** [comment]
set LANG=<lang>

**Comment by hunorbsd** [comment]
thanks for the fast reply
it does not seems to work, the hints are changing but everything else remains the same

**Comment by adamyg** [comment]
Confirm the lang is available under the locales, default:  "C:/Program Files (x86)/Midnight Commander/locale"
note, scope varies from locale.

**Comment by chipbite** [comment]
To clarify / elaborate on `set LANG =` :  

### Options:
* (1) Use set in terminal before starting mc. Like so

```
set LANG=en_EN.UTF-8 
mc
```

* (2) Set environment variable in windows. (windows, type "env", select change environemtn variables, click through two dialogue, add new)

![image](https://user-images.githubusercontent.com/559199/156943227-a477405c-20ec-4409-b9db-4c78d2a73ba8.png)

**Comment by adamyg** [comment]
nice doc, thanks
