### ISSUE TITLE
Midnight Commander is not fully portable

### ISSUE THREAD

**Issue by skarsgal** [adamyg/mcwin32#2]
Midnight Commander is not fully portable because it writes in '%USERPROFILE%\Midnight Commander' instead of application folder.
Can You solve this issue ?
Thanks.

**Comment by eugenov** [comment]
Will variables MC_DATADIR and MC_PROFILE_ROOT help?

**Comment by adamyg** [comment]
MC_DATADIR shall override the system configuration local, 
whereas MC_PROFILE_ROOT shall override the user profile location.
See "mc -F" for their affects once set.
