### ISSUE TITLE
How to change Language?

### ISSUE THREAD

**Issue by mikekgr** [adamyg/mcwin32#27]
Dear Sirs,
when I started mc in my Windows 10 pc, mc is started in Greek language and this is probably getting from my Windows 10 region settings that is Greece/Greek, even my selected language for Windows is English and all in Windows U.I. is in English. 
That is super annoying. How can select or force mc to started in English language? 
Thanks and Best Regards,
Mike Kranidis

**Comment by adamyg** [comment]
Please confirm version information, build 226 is the latest

**Comment by norbux** [comment]
I solved this by removing all the locales except english.  In my instalation those locales are in C:\Program Files (x86)\Midnight Commander\locale. So I just backed up the original folder and left the original only with en_GB. But, yeah, it would be cool to have  a way to select the locale from the configuration.

**Comment by mikekgr** [comment]
Thanks, probably I will follow your trick!

**Comment by adamyg** [comment]
the locale selection, build 266+ follows the logic:

- LC_ALL environment variable.
- LC_MESSAGES environment variable.
- LANG environment variable.
- LANGUAGE environment variable.
- GetThreadLocale() which should be the user's default locale.
  
Setting any of above before starting mc should impact the locale.

**Comment by norbux** [comment]
> the locale selection, build 266+ follows the logic in order:
> 
> * LC_ALL environment variable.
> * LC_MESSAGES environment variable.
> * LANG environment variable.
> * LANGUAGE environment variable.
> * and by default, results of GetThreadLocale(); which should be the user's default locale.
> 
> Setting any of above before starting mc should impact the locale; note the first encountered is utilized,

Great, thanks @adamyg

**Comment by adamyg** [comment]
resolved

**Comment by mikekgr** [comment]
Many thanks dear developer!
