### ISSUE TITLE
Where is mcedit binary file?

### ISSUE THREAD

**Issue by caffeine-mgn** [adamyg/mcwin32#28]
Sometimes I need just quickly edit some file. And usually I can do it on Linux with `mcedit`

**Comment by adamyg** [comment]
mcedit is an alias for mc, aka a symlink under unix.; copy mc.exe as mcedit.exe to emulate.

**Comment by AndiLeni** [comment]
@adamyg I tried to simply use `mc myfile.txt` to open the editor, but instead it opens midnightcommander in the current folder.
Is there an option to quickly open a file in mc's editor directly?

**Comment by adamyg** [comment]
shall repackage mc as mcedit in next release; waiting on 4.8.29

**Comment by adamyg** [comment]
build-228

**Comment by adamyg** [comment]
released

**Comment by myfonj** [comment]
I'm unable to see any `mcedit` executable neither in 228 nor 229 ZIP dists, was it really released?

However, from what I have tried, creating hardlink mcedit.exe -> mc.exe with 

```batch
mklink /H mcedit.exe mc.exe
```

seems to do the trick, so could be manual workaround for the mean time.
(As well as simply duplicating `mc.exe` and renaming the duplicate to `mcedit.exe`.)

**Comment by adamyg** [comment]
Just copy mc.exe to mcedit; the same action is done when packaged
.

**Comment by myfonj** [comment]
Sure, that's the second ("duplicating") option I have mentioned. But wouldn't be better if users of ZIP archives "installations" would not have to do that and had it prepared already? Is it possible to distribute it with duplicate or even better some kind of (smaller) proxy launcher that would behave like a symlink?
