### ISSUE TITLE
I am a Windows 11 user and I want to apply it to cmd.

### ISSUE THREAD

**Issue by oklokl** [adamyg/mcwin32#31]
I want to make it work in cmd terminal
mc
I hope it works if you enter the command
What should I do?

I searched and couldn't find it.
thank you.

**Comment by adamyg** [comment]
I don't have a Windows11 target. More details required, thanks

**Comment by oklokl** [comment]
setx Path "%PATH%;C:\Windows\SysWow64 
Let's do it. I hope it goes well.
And it was disappointing that there was no shift file drag function.

**Comment by adamyg** [comment]
I don't manage the winget image; advice trying the latest release directly.
https://github.com/adamyg/mcwin32/releases/tag/4.8.28.227

**Comment by oklokl** [comment]
thank you. By warning me that Avast Antivirus is suspicious. I sent him data and got his permission. Error..
It works fine now. thank you.
It works well.
Recently I came to know 'winget' and fell in love. haha.
The installation was automatic and it was so convenient.
I hope it will be updated someday.
(If it is updated, it would be nice to add an optional function. Option menu function to apply 'cmd')
It is installed automatically by the user. It looks like you need this option.
Options that can be set after installation or.. Ask for options after installation is complete Various ideas.. Lightly suggest
thank you.

I don't speak English, so I use google translator.
