### ISSUE TITLE
mc 4.8.29

### ISSUE THREAD

**Issue by adamyg** [adamyg/mcwin32#32]
Coming soon: https://midnight-commander.org/

**Comment by Neustradamus** [comment]
@adamyg: It has been released:
- https://midnight-commander.org/wiki/NEWS-4.8.29

**Comment by adamyg** [comment]
build-228

**Comment by adamyg** [comment]
Possible libssh2 release soon, #45

**Comment by adamyg** [comment]
released

**Comment by Neustradamus** [comment]
@adamyg: Thanks for update but there is a 4.8.30 (2023-08-13):
- https://github.com/adamyg/mcwin32/issues/57
