### ISSUE TITLE
Can not use on non graphical windows (like docker :( )

### ISSUE THREAD

**Issue by GillesRonsin** [adamyg/mcwin32#33]
Hi, 
its a pitty, it seems than mc use graphical features on windows.. so it can't be use into light docker windows server images

is there a really text mode (like linux) ?

**Comment by GillesRonsin** [comment]
Hi Adam,

Its ok.
I was running into a Windows container nanoserver which not allow 32 bits applications
In a full server it is ok

Thx

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :mercredi 13 juillet 2022 14:04
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [adamyg/mcwin32] Can not use on non graphical windows (like docker :( ) (Issue #33)


mc runs within a windows console;, it is not running graphical ui; more information required.
try firstly by running in b&w, --nocolor mode.

**Comment by adamyg** [comment]
win64 build is already possible, see Actions/mingw64. The larger obstacle is the available api's, to extent it is identified under a separate family to standard applications; WINAPI_FAMILY_SERVER verses WINAPI_FAMILY_DESKTOP.

**Comment by adamyg** [comment]
still look at 64bit build at a later time.
