### ISSUE TITLE
Escape-Letter sequences not working

### ISSUE THREAD

**Issue by proski** [adamyg/mcwin32#37]
Following sequences are not working, even when the Escape timeout is long enough and I press the keys in quick succession.

Escape-? should show the Find File dialog
Escape-c should show the Quick CD dialog
Escape-H should show the command history

Instead, I'm just getting the symbols on the command line.

Those are the sequences I use regularly. There are more Escape sequences that are not working. It looks like only Escape-Number sequences are working.

**Comment by proski** [comment]
Escape-Enter is also broken.

**Comment by adamyg** [comment]
released build-229
