### ISSUE TITLE
winget has wrong version

### ISSUE THREAD

**Issue by vlad196** [adamyg/mcwin32#53]
The version on winget and the version of the program itself differ in the name, because of it, winget updates "MC" every time it checks for updates

winged writes:
Installed version: 4.8.28 (build: 20220618-227)
Available for update: 4.8.28

**Comment by adamyg** [comment]
Not something i directly maintain: https://winget.run/pkg/GNU/MidnightCommander

**Comment by adamyg** [comment]
run with winget --verbose and attach; remove personal details if require;; thx

**Comment by vlad196** [comment]
> MC

Thanks' a lot!
