### ISSUE TITLE
proxyjump in Shell-link won't work

### ISSUE THREAD

**Issue by Kyogre** [adamyg/mcwin32#54]
I made aliases config in `C:\Users\%USERNAME%\.ssh\config` and have written aliases with proxyjumps there.
If I try to connect via `cmd` using `ssh <alias>` command, it asks passwords and connects successfully.

If I connect using alias via `Shell-link` feature in `mc` on my linux OS on the same PC, it connects without a problems too.

But if I try to connect on Windows using alias via `Shell-link` feature in `mcwin32` (v4.8.29), I get error `Cannot chdir to "/sh://<alias>"`

**Comment by adamyg** [comment]
unsure if a libssh2 supported future

**Comment by sloth5649** [comment]
A possible workaround is to use the ProxyCommand directive in the config file.
Mine looks like this:

Host ProxyJump_server
  HostName <ProxyJump_server ip address>
  User ....
  IdentityFile ....
 
Host <server>
  HostName <server ip address>
  User ....
  IdentityFile ....
  ProxyCommand ssh -q -W %h:%p ProxyJump_server

**Comment by sloth5649** [comment]
A possible workaround is to use the ProxyCommand directive in the config file.
Mine looks like this:

Host ProxyJump_server
HostName ProxyJump_server ip address
User ....
IdentityFile ....

Host server
HostName server ip address
User ....
IdentityFile ....
ProxyCommand ssh -q -W %h:%p ProxyJump_server

**Comment by Kyogre** [comment]
Yeah, your workaround works great for me too. Thanks

**Comment by Kyogre** [comment]
Working fine now on `mcwin32 4.8.31`
