### ISSUE TITLE
Midnight Commander 4.8.30 (2023-08-13)

### ISSUE THREAD

**Issue by Neustradamus** [adamyg/mcwin32#57]
@adamyg: Can you update to 4.8.30?

Midnight Commander 4.8.30 (2023-08-13):
- https://github.com/MidnightCommander/mc/tags
- https://github.com/MidnightCommander/mc/releases/tag/4.8.30
- https://midnight-commander.org/wiki/NEWS-4.8.30

Thanks in advance.

**Comment by adamyg** [comment]
build-229 released
