### ISSUE TITLE
Mbed TLS 3.4.1

### ISSUE THREAD

**Issue by Neustradamus** [adamyg/mcwin32#58]
@adamyg: Mbed TLS 3.4.1 (2023-08-03):
- https://github.com/Mbed-TLS/mbedtls/releases
- https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.4.1

**Comment by adamyg** [comment]
build-229 released

**Comment by Neustradamus** [comment]
@adamyg: What version?

The latest build?
Mbed TLS 3.5.1?

**Comment by adamyg** [comment]
#67
