### ISSUE TITLE
Windows 64 (x64) release builds are missing

### ISSUE THREAD

**Issue by Neustradamus** [adamyg/mcwin32#60]
Dear @adamyg,

It is possible to create Windows x64 release builds?

We are in 2023, and there are not at this time...

Windows x64 exists since Windows XP, more 20 years old.

Thanks in advance.

**Comment by adamyg** [comment]
x64 builds are available within CI

**Comment by Neustradamus** [comment]
@adamyg: Thanks for your answer, I had not received your edited text.
I have seen the file but can you publish directly an .exe file and not a .zip file?

In more, have you received my email?

**Comment by adamyg** [comment]
x64 beta build-230
