### ISSUE TITLE
MC fails on a subst - drive

### ISSUE THREAD

**Issue by winspool** [adamyg/mcwin32#65]
I merged the contents of my old second drive to a subdirectory to "C:"
and use "mklink" and "subst.exe" to make the same drive letter available as i used before.
(In my use case, "S:" is a subst to "C:\_s" and "C:\_s" is a link to "C:\data\src")

In the console, changing to the subst drive with "S:" works, "dir" works,
but starting "mc" fails:
1: The mc Dialog "Kann Verzeichniss nicht lesen" comes up ("Can`t read directory")
2: This Dialog is not active and can`t be closed with "Enter", but a second "Enter" works
3: Main ui of mc comes up, but the panel has no files or directiories

**Comment by adamyg** [comment]
shall review, have not encountered/used subst's drives in many years.

**Comment by adamyg** [comment]
testing a subst directories works without issue, why not use "subst S: C:\data\src" ?

**Comment by adamyg** [comment]
retest against latest, thx
