### ISSUE TITLE
`\` seems to be ignored

### ISSUE THREAD

**Issue by fekir** [adamyg/mcwin32#71]
In `mc` under GNU/Linux systems (and cygwin for what it is worth) the `\` is use at least in three different places

 1) You can type `a\`, and `a\` will appear in the shell (I'm not sure if it is named shell, I hope it is clear what I mean by that)

2) The directory hotlist is opened with `Ctrl+\`

3) You can open the unselect dialog directly with `\`

In mcwin32, none of those three scenarios work.

Typing `a\` only shows `a` in the shell

`Ctrl+\` does not do nothing, and  `\` does not do nothing either.

Thus, it seems that `\` is ignored in mc, I've tested in `cmd.exe`, `powershell`, and also tried to start the executable directly

**Comment by adamyg** [comment]
Plz check version.

**Comment by fekir** [comment]
I'm using version 4.8.30, also retested with 4.8.29, there is no difference

**Comment by adamyg** [comment]
Confirm input is UTF-8 under "Display Bits"

**Comment by fekir** [comment]
![image](https://github.com/adamyg/mcwin32/assets/11912465/3a96b5fa-83f0-49be-93ba-f3e7e7df61c9)


Confirmed, I've tried toggling the "full 8 bits input", but it did not make a difference.

**Comment by adamyg** [comment]
Noted "Lokale Einstellungen" within the screen-shot assume German locale is active.
Are you using a German KB layout (00000407) ? https://kbdlayout.info/KBDGR/

**Comment by fekir** [comment]
The system was installed as a German system.

In my user account I've changed the language to English.

My keyboard layout is German.

I've just tried, non-ASCII characters like ä, ö, and ü are entered and rendered without issues.

**Comment by adamyg** [comment]
AltGr translation issue

**Comment by fekir** [comment]
Yes, seems to be, I am not able to enter following characters too: `{[]}~`

Additional information:

If I leave my Windows settings unchanged, connect from a Linux machine with `ssh` I have exactly the same issue.


If I change my Windows keyboard layout to something else with a `\` key, I am able to enter `\` (thus no need to change the user language).
