### ISSUE TITLE
Switch between drives

### ISSUE THREAD

**Issue by fekir** [adamyg/mcwin32#72]
In Unix-like system, there is the root directoy `/`.

External drives are mounted somewhere under it, thus it is generally possible to access all folders by traversing a tree.

In Windows, as Paths represented as `C:/blabla`, it is not, as an USB drive will be mounted, for example, as `D:/`.

In `explorer.exe` there is a "virtual folder" from which it is possible to access `C:/`, other partitions if available and network drives.

As far as I know, there is no way from mc for switching between `C:/` and `D:/` (typing the `cd` command out and using a bookmark are possible workarounds).

I think it would be nice to have a virtual folder similar to `explorer.exe` (thus a parent of `C:/`),  but I'm not sure what side-effects such a virtual folder could have.
Otherwise some action that enlists all mounted drives (local or network) and asks to which to switch?
For what is worth, far (another file manager like mc from the command line: https://www.farmanager.com/) uses Alt+F1 for asking to which drive to change

**Comment by fekir** [comment]
Alt+F1 seems to also work in mcwin32, thus this issue can be closed.

Is it documented somewhere?
Somehow I do not find this feature described anywhere.

**Comment by adamyg** [comment]
ALt-F1 and Alt-D present a <Change Drive> dialog.
also when a drive is present within the a cd command, examples "cd D:<dir> or cd D:." the same can occur.

**Comment by adamyg** [comment]
```cd <drive>:``` doesn't always behave as expected, 
plus ```cd <drive>:```` displays ```.```` and not the resulting target dir.
