### ISSUE TITLE
Very slow on network locations

### ISSUE THREAD

**Issue by fekir** [adamyg/mcwin32#73]
When working on a mounted network location in Windows, `mc` is extremely slow.

It seems to hang (even for 1-2 seconds) every time I change folder, and I cannot open, for example, the user menu in the meantime.

Once the content of the folder is shown, `mc` feels normal again.

It seems thus it has to do with querying the list of files, but other file managers, for example, `explorer.exe` and `far.exe` do not have this issue.

**Comment by adamyg** [comment]
mc scans full directory, pulling status of each since element; current design.

**Comment by adamyg** [comment]
All directory elements are loaded on open; otherwise sort order wont function.

**Comment by adamyg** [comment]
current design; only suitable if the display is unordered.
