### ISSUE TITLE
mc can't show the size of the large files.

### ISSUE THREAD

**Issue by TByte007** [adamyg/mcwin32#83]
For example dir command shows 8540770496 (~8G) bytes and mc shows "16384P" same is true for 16069403904 (~16G) bytes and 4108916384 (~4G) bytes.
Basically almost every large file (over 4G probably ?) is shown as "16384P" but not every. I have a file which is 13831319616 bytes and it is shown as "924236K" which is not even close to the size.
I'm guessing there is a size var overflowing somewhere. My hunch is that if the value in GB is closely divisible by 4 you get "16384P" if not you get $size mod(%) 4,294,967,296 or something along those lines.

**Comment by adamyg** [comment]
duplicate #35
