### ISSUE TITLE
sftp does not use ssh key

### ISSUE THREAD

**Issue by fekir** [adamyg/mcwin32#86]
Hello, it seems that mc does not use my ssh key located at `~/.ssh`

I've an entry in ~/.ssh/config with `HostName`, `User` and `IdentityFile`, and I can use ssh for logging in successfully to the remote.

According to https://github.com/adamyg/mcwin32/issues/1, ssh keys should be supported.

Are there known limitations?
Is there something I can do (logging?) for debugging this issue?

**Comment by adamyg** [comment]
implementation leverages libssh2, not OpenSSH; currently only ~/.ssh/known_hosts is utilized.

**Comment by adamyg** [comment]
MC: https://midnight-commander.org/ticket/3039. long pending issue.

**Comment by fekir** [comment]
I'm not sure about the status of https://midnight-commander.org/ticket/3039 and https://midnight-commander.org/ticket/4506, but I use use daily mc with sftp + ssh keys + aliases in ~/.ssh/config, both on linux and windows (with cygwin)

**Comment by adamyg** [comment]
Try running the OpenSSH agent
