### ISSUE TITLE
Directory hotlist CTRL+\ not working

### ISSUE THREAD

**Issue by risefall123** [adamyg/mcwin32#92]
It seem if I want to enter in the "Directory hotlist" with the CTRL+\ combination, it doesn't work.

In Linux it works.

**Comment by adamyg** [comment]
AltGr issue?

![image](https://github.com/user-attachments/assets/ea3f2881-a310-4b1d-a9cc-c1c4b7d3f427)

**Comment by risefall123** [comment]
I didn't get your answer, sorry.

After trying some keys I found that the hotkey is CTRL+"ù".

It's maybe because I'm on italian keyboard?

But in Linux I use the same italian keyboard.

Maybe for the language (I see on Windows MC in italian while on Linux in english)?

Anyway, the issue is for me solved with CTRL+"ù".

**Comment by adamyg** [comment]
See AltGr discussion under #71, confirm if **AltGr [x]** is enable; dialog example 

![372346622-ea3f2881-a310-4b1d-a9cc-c1c4b7d3f427](https://github.com/user-attachments/assets/58d957e2-3f2a-4797-b7ac-2e0571c662a3)

**Comment by risefall123** [comment]
If I run "kbtest test" I see the (correct) italian keyboard and every key I press is correct showed.

I fear that, hotlist apart, other hotkeys will be mistaken.
